### ISSUE TITLE
Unable to complete Pull request

### ISSUE THREAD

**Issue by hwankyusong** [CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment#10]
<img width="1255" alt="Screen Shot 2021-09-28 at 9 02 37 AM" src="https://user-images.githubusercontent.com/12506177/135092155-14328985-0ffe-4714-bd0a-40e81171ede0.png">

**Comment by shots47s** [comment]
You have to commit your code into your fork, you fork right now is identical to the main repo.

**Comment by hwankyusong** [comment]
Right, sorry.
