### ISSUE TITLE
tests file not added to without_pyscf branch

### ISSUE THREAD

**Issue by manishsainani** [CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment#26]
I am working on Windows and I used the without_pyscf branch for the 2nd assignment. Now I am looking to fetch upstream my local repository to this branch but I realized that without_pyscf branch doesnt have the tests file. If I fetch upstream the main branch, it would create problems in my current code as I coded without pyscf, right?

**Comment by shots47s** [comment]
Ah, give me 20 minutes, I will merge up the test changes into that branch, and then you should be good.

**Comment by manishsainani** [comment]
Thank you so much

**Comment by shots47s** [comment]
Ok, I have merged up the changes, so the testing rig should now work on that branch.

**Comment by manishsainani** [comment]
Thank you
