### ISSUE TITLE
Error in one test

### ISSUE THREAD

**Issue by manishsainani** [CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment#28]
def test_solve_Roothan_equations(mol_h2o):
    Huv = SCF.calc_hcore_matrix(Tuv, Vuv)
    Duv = SCF.calc_initial_density(mol_h2o)
    Fuv= SCF.calc_fock_matrix(mol_h2o, Huv, eri, Duv)
    mo_e, mo_c = SCF.solve_Roothan_equations(Fuv, Suv)
    assert mo_e[0] == ([-32.5783029, -8.08153571, -7.55008599,
                                     -7.36396923,  -7.34714487, -4.00229867,
                                     -3.98111115])

    assert mo_c[0, :] == ([-1.00154358e+00, 2.33624458e-01,
                                        1.31048670e-17, -8.56842145e-02,
                                        -1.26828709e-31, -4.82226067e-02,
                                        1.47103574e-17])

Error: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

tests\SCF\test_SCF.py:53: ValueError
FAILED tests/SCF/test_SCF.py::test_solve_Roothan_equations - ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() 

How can I fix this?

**Comment by shots47s** [comment]
This was addressed in a previous issue:

pytest has an appox function that does rounding, and the sign of the values in the eigenvector matrix may not be the same across different machines, so you cannot test against the signed value.
