### ISSUE TITLE
unable to push

### ISSUE THREAD

**Issue by sagar807** [CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment#31]
I am trying to push from my fork's main to the class repository's main but unable to do so and getting the following error 
 ! [remote rejected] main -> main (permission denied)
 error: failed to push some refs to 'https://github.com/sagar807/HF_SCF_Assignment.git'
please help me with this

**Comment by shots47s** [comment]
You have to create a pull request, not push directly. If you have already
made a pulle request, then further commits to your fork will automatically
become part of your PR.

**Comment by shots47s** [comment]
Please commit your test changes to your fork, so they are added to the PR, we can look at it in class today if needed.
